### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by RPerrodin** [Visual-Dawg/space_dots#1]
In the `~/.config/hypr/` repository, the files `monitors.conf` and `workspaces.conf` are called by _hyprland.conf_ but are missing.

**Comment by vdawg-git** [comment]
Thank you for reporting this :)
I am not sure how this happened, but you can find them on my main dots [here](https://github.com/Visual-Dawg/dotfiles) 

This repo is more of a theme, than actual dotfiles.
I will update the readme accordingly

**Comment by vdawg-git** [comment]
I removed those two lines from the config.
If you have questions or need help, feel free to hit me up or comment again :D
