### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by salahu01** [Visual-Dawg/space_dots#3]

**Comment by vdawg-git** [comment]
due to copyright thingy I do not provide them

**Comment by salahu01** [comment]
Can you share assets personally ?

**Comment by vdawg-git** [comment]
You can download the first three cowboy bebop episodes (you see in the code the timestamps I used, but you might need to adjust them) and some random vinyl scratches. 
That's all there is I think

Sharing them personally would be too much work for me, sorry
