### ISSUE TITLE
Is there a link to the background video used in the project?

### ISSUE THREAD

**Issue by themistrinel** [Visual-Dawg/space_dots#6]
I really liked the background video in the project and was wondering if there’s a public link to it or if it's hosted somewhere I can access?

**Comment by vdawg-git** [comment]
Its made out of clips from [Cowboy Bebop](https://www.imdb.com/title/tt0213338/). 
I used [mpvpaper](https://github.com/GhostNaN/mpvpaper) programmatically to cut them dynamically, so there is no video file.

https://github.com/vdawg-git/space_dots/blob/main/.other/mpv.mjs
Has the code and I think I used clips from the first three episodes :)
